### ISSUE TITLE
delete

### ISSUE THREAD

**Issue by akane-tendo** [Simbiat/lodestone-parser#1]
********

**Comment by Simbiat** [comment]
Indeed, you are correct, the condition is not necessary there. I've updated the code.

To be honest, I was planning to retire the library. Or rather I wanted to merge it with appropriate module in https://github.com/Simbiat/simbiat.ru (so that appropriate "grab" function would be in respective entity types and not all over. Such merger would mean [potential] retirement of some of the parsers in this library, including search.
Can you, please, elaborate on your use case? Depending on it, I may be able to implement it as part of the API for the website.

**Comment by Mhitra** [comment]
Thank you! Really appreciated! :)
Ohh... I'm just using this code (the only one support PHP 8) to grab my FC members :)
And search by name/server in case the member is new but lodestone is not updated yet.
Pretty much an updated FC member list in real-time.
Thanks again!

**Comment by Simbiat** [comment]
That's what https://www.simbiat.ru/fftracker/search does, actually (or at least, did: was not checking on it, since I am rebuilding a lot of things in https://github.com/Simbiat/simbiat.ru). Except it currently does not mark new members (this is in todo list for new UI). Code for it can be found in https://github.com/Simbiat/simbiat.ru/tree/master/lib/simbiat.ru/src in `FFTracker.php` and `FFTModules` folder, but I'd recommend waiting till I complete reorganization of the code.
It is also planned to allow to force refresh entities. At least, for registered users, once registration is up. At least for owners of the entities.
